### PR TITLE
Add an after function

### PR DESCRIPTION
**Pull request by jeffhsta**
I added an after function to be possible execute code after run the contract test.

Issue #3

### CODE REVIEW

**Comment by robinjmurphy** [comment]
Thanks @jeffhsta. This is a nice feature. Do you think you'd be able to run a test for it? You should be able to follow the same pattern as we did for `before` https://github.com/bbc/consumer-contracts/blob/master/test/contract.js#L185-L224.

**Comment by jeffhsta** [comment]
@robinjmurphy Sure, I can do it, I will commit in this same PR

**Comment by jeffhsta** [comment]
@robinjmurphy I created tests for the after function based on other ones.

Let me know if there is anything that I missed

**Comment by robinjmurphy** [comment]
Thanks @jeffhsta. Will merge this now and get a new release out tomorrow for you.

**Pull request merged**
