### PR TITLE
Use filehound

### PR DESCRIPTION
**Pull request by nspragg**
Minor refactor to use FileHound for finding consumer contracts.

### CODE REVIEW

**Comment by robinjmurphy** [comment]
I get this error when running in Node 0.10.x:

```
/Users/robinmurphy/Development/consumer-contracts/node_modules/filehound/lib/filehound.js:56
    this.searchPaths = new Set();
                           ^
ReferenceError: Set is not defined
    at new FileHound (/Users/robinmurphy/Development/consumer-contracts/node_modules/filehound/lib/filehound.js:56:28)
    at Function.create (/Users/robinmurphy/Development/consumer-contracts/node_modules/filehound/lib/filehound.js:199:14)
    at Command.module.exports (/Users/robinmurphy/Development/consumer-contracts/lib/runner.js:65:13)
    at Command.listener (/Users/robinmurphy/Development/consumer-contracts/node_modules/commander/index.js:301:8)
    at Command.emit (events.js:98:17)
    at Command.parseArgs (/Users/robinmurphy/Development/consumer-contracts/node_modules/commander/index.js:615:12)
    at Command.parse (/Users/robinmurphy/Development/consumer-contracts/node_modules/commander/index.js:458:21)
    at Object.<anonymous> (/Users/robinmurphy/Development/consumer-contracts/lib/cli.js:13:9)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:935:3
```

**Comment by robinjmurphy** [comment]
Might be good to add 0.10 and 0.12 to https://github.com/nspragg/filehound/blob/master/.travis.yml#L2-L4 if you're looking to support them. That way Travis will make sure they're all happy.

**Comment by nspragg** [comment]
Thanks Robin. Good idea. 

As for the fix. I'm aware of two options: 

1) require 'babel-polyfill' in the runner.js (consumer contracts)
2) Refactor filehound not to use a set (easy enough and probably a better fix)

**Comment by nspragg** [comment]
Patched for node 0.10.x

**Comment by robinjmurphy** [comment]
Should be able to remove `recursive-readdir` now right?

**Pull request merged**
